// example/angular/src/app/pages/payment-details/payment-details.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-payment-details',
  templateUrl: './payment-details.component.html',
  styleUrls: ['./payment-details.component.scss']
})
export class PaymentDetailsComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<app-page-title title="Payment Details"></app-page-title>

<form role="form"
      class="st-form"
      autocomplete="off"
      fxLayout="column"
      novalidate>

  <fieldset class="st-form-fieldset">
    <legend>Payment details:</legend>
    <div fxLayout="row" fxLayoutGap="10px">
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Price</mat-label>
        <input matInput
               type="text"
               name="myBillPrice"
               id="st-form-price"
               data-st-name="billingprice"
        />
      </mat-form-field>
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Amount</mat-label>
        <input matInput
               type="number"
               name="myBillAmount"
               id="example-form-amount"
               placeholder="myBillAmount"
               data-st-name="billingamount"
               autocomplete="amount"
        />
      </mat-form-field>
    </div>

    <div>
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Type of payment</mat-label>
        <mat-select placeholder="myBillSubscribe" id="st-form-subscribe">
          <mat-option value="one-off payment">one-off payment</mat-option>
          <mat-option value="monthly payment">monthly payment</mat-option>
        </mat-select>
      </mat-form-field>
    </div>
  </fieldset>

  <button mat-flat-button color="accent" type="submit" fxFlex routerLink="/personal-data">Continue</button>
</form>

// example/reactjs-payments/src/pages/payment-details.jsx
import React from 'react';
import Layout from '../components/layout/layout';
import { Heading } from '../components/heading/heading';

const PaymentDetails = () => {
  return (
    <Layout>
      <Heading title={'Payment Details'} />
      <fieldset className="st-form__fieldset">
        <legend>Payment details:</legend>
        <div className="st-form__section st-form__section--horizontal">
          <div className="st-form__field">
            <label htmlFor="st-form-price" className="st-form__label">
              price:
              <abbr title="required" aria-label="required">
                *
              </abbr>
            </label>

            <input
              type="text"
              name="myBillPrice"
              value="10"
              id="st-form-price"
              className="st-form__input"
              placeholder="myBillPrice"
              data-st-name="billingprice"
              disabled
            />
          </div>
          <div className="st-form__field">
            <label htmlFor="example-form-amount" className="st-form__label">
              amount:
              <abbr title="required" aria-label="required">
                *
              </abbr>
            </label>
            <input
              type="number"
              name="myBillAmount"
              id="example-form-amount"
              className="st-form__input"
              placeholder="myBillAmount"
              data-st-name="billingamount"
              autoComplete="amount"
            />
          </div>
        </div>
        <div className="st-form__section st-form__section--horizontal">
          <div className="st-form__field">
            <label htmlFor="st-form-subscribe" className="st-form__label">
              type of payment:
              <abbr title="required" aria-label="required">
                *
              </abbr>
            </label>
            <select
              name="myBillSubscribe"
              id="st-form-subscribe"
              className="st-form__input"
              placeholder="myBillSubscribe"
              autoComplete="subscribe"
            >
              <option value="one-off payment">one-off payment</option>
              <option value="monthly payment">monthly payment</option>
            </select>
          </div>
        </div>
      </fieldset>
    </Layout>
  );
};
export default PaymentDetails;
