// example/angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

interface LinkDefinition {
  route: string;
  title: string;
  id?: string;
}

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  readonly links: LinkDefinition[] = [
    { route: 'home', title: 'Home', id: 'home' },
    { route: 'payment-details', title: 'Payment details', id: 'payment-details' },
    { route: 'personal-data', title: 'Personal data', id: 'personal-data' },
    { route: 'contact-data', title: 'Contact data', id: 'contact-data' },
    { route: 'payment', title: 'Payment', id: 'payment' }
  ];
}

<mat-toolbar class="top-header">
  <div class="container" fxLayout="row" fxLayoutAlign="start center">
    <img src="/assets/tp-logo.jpg" class="logo" alt="Trust Payments logo">
    <h1>Angular Example</h1>
  </div>
</mat-toolbar>
<mat-toolbar>
  <div class="container">
    <nav mat-tab-nav-bar color="accent">
      <a *ngFor="let link of links"
         mat-tab-link
         [routerLink]="link.route"
         [id]="link.id"
         routerLinkActive
         #rla="routerLinkActive"
         [active]="rla.isActive">
        {{link.title}}
      </a>
    </nav>
  </div>
</mat-toolbar>

// example/vuejs/src/components/Header.vue
<template>
  <div class="container header">
    <img class="top-logo" alt="Trust Payments logo" src="../assets/tp-logo.jpg">
    <h1 class="top-title">VueJS Example</h1>
  </div>
  <NavMenu></NavMenu>
</template>

<script>
import NavMenu from './NavMenu.vue';

export default {
  name: 'Header',
  components: { NavMenu },
};
</script>

<style scoped lang="scss">
  @import "../styles/variables";

  .header {
    display: flex;
    align-items: center;
  }

  .top-title {
    color: $color-accent;
    font-weight: normal;
  }

  .top-logo {
    max-width: 150px;
    margin-right: 20px;
  }
</style>
