// example/angular/src/app/components/payment-form/payment-form.component.ts
import { AfterViewInit, Component, Input } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { IPageOptions } from '../../services/page-options.interface';

declare const SecureTrading: any;

@Component({
  selector: 'app-payment-form',
  templateUrl: './payment-form.component.html',
  styleUrls: ['./payment-form.component.scss']
})
export class PaymentFormComponent implements AfterViewInit {
  @Input() config: any;
  @Input() pageOptions: IPageOptions;
  private st: any;

  constructor(private snackBar: MatSnackBar) {}

  ngAfterViewInit(): void {
    this.st = SecureTrading(this.config);
    this.st.Components(this.config.components);
    this.st.VisaCheckout(this.config.visaCheckout);
    this.st.ApplePay(this.config.applePay);

    if (!this.config.successCallback) {
      this.st.on('success', () => {
        this.snackBar.open('Payment completed successfully', 'close', {
          verticalPosition: 'top',
          panelClass: 'success'
        });
      });
    }

    if (!this.config.errorCallback) {
      this.st.on('error', () => {
        this.snackBar.open('An error occurred', 'close', { verticalPosition: 'top', panelClass: 'error' });
      });
    }

    if (!this.config.submitCallback) {
      this.st.on('submit', data => {
        console.log(`This is what we have got after submit ${JSON.stringify(data)}`);
      });
    }
  }

  updateJwt(): void {
    if (this.pageOptions.updatedJwt) {
      this.st.updateJWT(this.pageOptions.updatedJwt);
    }
  }
}

<form [id]="pageOptions.formId"
      role="form"
      name="st-form"
      action="https://www.example.com"
      class="st-form"
      autocomplete="off"
      novalidate>

  <div id="st-popup" class="st-popup"></div>

  <div id="st-notification-frame" class="st-form__group notification-frame"></div>

  <fieldset class="st-form-fieldset">
    <legend>Payment details:</legend>
    <div fxLayout="row" fxLayoutGap="10px">
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Price</mat-label>
        <input matInput
               type="text"
               name="myBillPrice"
               id="st-form-price"
               data-st-name="billingprice"
               (change)="updateJwt()"
        />
      </mat-form-field>
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Amount</mat-label>
        <input matInput
               type="number"
               name="myBillAmount"
               id="example-form-amount"
               placeholder="myBillAmount"
               data-st-name="billingamount"
               autocomplete="amount"
               (change)="updateJwt()"
        />
      </mat-form-field>
    </div>

    <div fxLayout="row" fxLayoutGap="10px">
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Name</mat-label>
        <input matInput
               type="text"
               name="myBillName"
               id="st-form-last-name"
               placeholder="Doe"
               data-st-name="billinglastname"
               autocomplete="family-name"
        />
      </mat-form-field>
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Email</mat-label>
        <input matInput
               type="email"
               name="myBillEmail"
               id="st-form-email"
               placeholder="test@mail.com"
               data-st-name="billingemail"
               autocomplete="email"
        />
      </mat-form-field>
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Phone</mat-label>
        <input matInput
               type="tel"
               name="myBillTel"
               id="st-form-phone"
               placeholder="+00 000 000 000"
               autocomplete="tel"
        />
      </mat-form-field>
    </div>

    <div>
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Type of payment</mat-label>
        <mat-select placeholder="myBillSubscribe" id="st-form-subscribe">
          <mat-option value="one-off payment">one-off payment</mat-option>
          <mat-option value="monthly payment">monthly payment</mat-option>
        </mat-select>
      </mat-form-field>
    </div>
  </fieldset>


  <fieldset class="st-form-fieldset">
    <legend>APM's:</legend>
    <div id="st-visa-checkout"></div>
    <div id="st-apple-pay"></div>
    <div id="st-google-pay"></div>
  </fieldset>

  <fieldset class="st-form-fieldset">
    <legend>Credit card details:</legend>
    <div fxLayout="row">
      <div>
        <div id="st-card-number"></div>
        <div id="st-expiration-date"></div>
        <div id="st-security-code"></div>
      </div>
      <div id="st-animated-card" fxLayoutAlign="center" fxFlex></div>
    </div>
  </fieldset>

  <div id="st-control-frame"></div>

  <div fxLayout="column" fxLayoutGap="10px">
    <button mat-flat-button color="accent" type="submit"
            *ngIf="!pageOptions.noSubmitButton"
            [id]="pageOptions.submitButtonId">Pay
    </button>
    <button mat-flat-button color="accent" type="submit"
            *ngIf="pageOptions.additionalButton"
            [id]="pageOptions.additionalButtonId">Additional Button
    </button>
  </div>

</form>

// example/vuejs/src/components/PaymentForm.vue
<template>
  <form class="st-form" v-bind:id="pageOptions.formId">
    <div id="st-popup" class="st-popup"></div>
    <div id="st-notification-frame" class="st-form__group"></div>
    <fieldset>
      <legend>Payment details</legend>
      <div class="form-row">
        <input type="text" placeholder="Price" class="st-input" @change="updateJwt()"/>
        <input type="text" placeholder="Amount" class="st-input" @change="updateJwt()"/>
      </div>
      <div class="form-row">
        <input type="text" placeholder="Name" class="st-input" />
        <input type="email" placeholder="Email" class="st-input" />
        <input type="phone" placeholder="Phone" class="st-input" />
      </div>
      <div class="form-row">
        <select class="st-select">
          <option disabled selected hidden>Type of payment</option>
          <option>one-off payment</option>
          <option>monthly payment</option>
        </select>
      </div>
    </fieldset>
    <fieldset>
      <legend>APM's</legend>
      <div id="st-visa-checkout"></div>
      <div id="st-apple-pay"></div>
    </fieldset>
    <fieldset>
      <legend>Credit card details</legend>
      <div class="st-form-container">
        <div class="card-details">
          <div id="st-card-number" class="form-row"></div>
          <div id="st-expiration-date" class="form-row"></div>
          <div id="st-security-code" class="form-row"></div>
        </div>
        <div class="animated-card">
          <div id="st-animated-card"></div>
        </div>
      </div>
      <div id="st-control-frame"></div>
    </fieldset>
    <div class="form-row">
      <button type="submit"
              class="st-button"
              v-if="!pageOptions.noSubmitButton"
              v-bind:id="pageOptions.submitButtonId">Pay</button>
    </div>
    <div class="form-row" v-if="pageOptions.additionalButton">
      <button type="submit"
              class="st-button"
              v-bind:id="pageOptions.additionalButtonId">Extra button</button>
    </div>
  </form>
</template>

<script lang="ts">
import { onMounted, defineComponent } from 'vue';
import loadLibrary from '@/services/load-library';
import loadConfig from '@/services/load-config';
import { useRoute } from 'vue-router';
import resolvePageOptions from '@/services/page-options/resolve-page-options';
import mergeOptions from '@/services/page-options/merge-options';

export default defineComponent({
  setup() {
    const { query } = useRoute();
    const pageOptions = resolvePageOptions(query);
    let st: any;

    onMounted(() => {
      loadLibrary().then((SecureTrading) => {
        loadConfig()
          .then((config) => mergeOptions(config, pageOptions))
          .then((config) => {
            st = SecureTrading(config);
            st.Components(config.components);
            st.VisaCheckout(config.visaCheckout);
            st.ApplePay(config.applePay);

            // if (!this.config.successCallback) {
            //   this.st.on('success', () => {
            //     this.snackBar.open('Payment completed successfully', 'close', {
            //       verticalPosition: 'top',
            //       panelClass: 'success'
            //     });
            //   });
            // }
            //
            // if (!this.config.errorCallback) {
            //   this.st.on('error', () => {
            //     this.snackBar.open('An error occurred', 'close', {
            //     verticalPosition: 'top', panelClass: 'error' });
            //   });
            // }
            //
            // if (!this.config.submitCallback) {
            //   this.st.on('submit', data => {
            //     console.log(`This is what we have got after submit ${JSON.stringify(data)}`);
            //   });
            // }
          });
      });
    });

    function updateJwt(): void {
      if (pageOptions.updatedJwt) {
        st.updateJWT(pageOptions.updatedJwt);
      }
    }

    return {
      pageOptions,
      updateJwt,
    };
  },
});
</script>

<style scoped lang="scss">
.st-form-container {
  display: flex;

  .card-details {
    display: flex;
    flex-grow: 1;
    flex-direction: column;
  }

  .animated-card,
  .animated-card > #st-animated-card {
    display: flex;
    flex-grow: 1;
  }
}
</style>
