// example/angular/src/app/pages/contact-data/contact-data.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-contact-data',
  templateUrl: './contact-data.component.html',
  styleUrls: ['./contact-data.component.scss']
})
export class ContactDataComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<app-page-title title="Contact Data"></app-page-title>

<form role="form"
      class="st-form"
      autocomplete="off"
      fxLayout="column"
      novalidate>

  <fieldset class="st-form-fieldset">
    <legend>Contact data:</legend>
    <div fxLayout="row" fxLayoutGap="10px">
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>E-mail</mat-label>
        <input matInput type="email" placeholder="test@mail.com"/>
      </mat-form-field>

      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Phone</mat-label>
        <input matInput type="tel" placeholder="+00 000 000 000"/>
      </mat-form-field>
    </div>

    <div fxLayout="row" fxLayoutGap="10px">
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Street</mat-label>
        <input matInput type="text" placeholder="Park Str."/>
      </mat-form-field>

      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>City</mat-label>
        <input matInput type="text" placeholder="Richmond"/>
      </mat-form-field>
    </div>
  </fieldset>

  <button mat-flat-button color="accent" type="submit" fxFlex routerLink="/payment">Continue</button>
</form>

// example/vuejs/src/views/ContactData.vue
<template>
  <PageTitle title="Contact data"/>
  <form class="st-form">
    <fieldset>
      <legend>Contact data</legend>
      <div class="form-row">
        <input type="email" placeholder="E-mail" class="st-input" />
        <input type="tel" placeholder="Phone" class="st-input" />
      </div>
      <div class="form-row">
        <input type="text" placeholder="Street" class="st-input" />
        <input type="text" placeholder="City" class="st-input" />
      </div>
    </fieldset>
    <div class="form-row">
      <button type="submit"
              class="st-button"
              @click="$router.push('payment')">Continue
      </button>
    </div>
  </form>
</template>

<script>
import PageTitle from '@/components/PageTitle.vue';

export default {
  name: 'ContactData',
  components: {
    PageTitle,
  },
};
</script>

<style scoped>

</style>
