// example/angular/src/app/pages/personal-data/personal-data.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-personal-data',
  templateUrl: './personal-data.component.html',
  styleUrls: ['./personal-data.component.scss']
})
export class PersonalDataComponent {
  readonly titles = ['Mr', 'Mrs', 'Ms', 'Miss', 'Dr'];
}

<app-page-title title="Personal Data"></app-page-title>

<form role="form"
      class="st-form"
      autocomplete="off"
      fxLayout="column"
      novalidate>

  <fieldset class="st-form-fieldset">
    <legend>Personal data:</legend>
    <div fxLayout="row" fxLayoutGap="10px">
      <mat-form-field appearance="outline" color="accent">
        <mat-label>Title</mat-label>
        <mat-select placeholder="title">
          <mat-option *ngFor="let title of titles" value="{{title}}">{{title}}</mat-option>
        </mat-select>
      </mat-form-field>

      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>First name</mat-label>
        <input matInput type="text"/>
      </mat-form-field>

      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Last name</mat-label>
        <input matInput type="text"/>
      </mat-form-field>
    </div>

    <div fxLayout="row" fxLayoutGap="10px">
      <mat-form-field appearance="outline" color="accent" fxFlex>
        <mat-label>Date of birth</mat-label>
        <input matInput type="date"/>
      </mat-form-field>
    </div>
  </fieldset>

  <button mat-flat-button color="accent" type="submit" fxFlex routerLink="/contact-data">Continue</button>
</form>

// example/vuejs/src/views/PersonalData.vue
<template>
  <PageTitle title="Personal data"/>
  <form class="st-form">
    <fieldset>
      <legend>Personal data</legend>
      <div class="form-row">
        <select class="st-select">
          <option disabled selected hidden>Title</option>
          <option>Mr</option>
          <option>Mrs</option>
          <option>Ms</option>
          <option>Miss</option>
          <option>Dr</option>
        </select>
        <input type="text" placeholder="First name" class="st-input" />
        <input type="text" placeholder="Last name" class="st-input" />
      </div>
      <div class="form-row">
        <input type="date" placeholder="Date of birth" class="st-input" />
      </div>
    </fieldset>
    <div class="form-row">
      <button type="submit"
              class="st-button"
              @click="$router.push('contact-data')">Continue
      </button>
    </div>
  </form>
</template>

<script>
import PageTitle from '@/components/PageTitle.vue';

export default {
  name: 'PersonalData',
  components: {
    PageTitle,
  },
};
</script>

<style scoped>

</style>
