// example/reactjs-payments/src/pages/personal-data.jsx
import React from 'react';
import Layout from '../components/layout/layout';
import { Heading } from '../components/heading/heading';

const PersonalData = () => {
  return (
    <Layout>
      <Heading title={'Personal Data'} />
      <fieldset className="st-form__fieldset">
        <legend>Personal data:</legend>
        <div className="st-form__section st-form__section--horizontal">
          <div className="st-form__field">
            <label htmlFor="st-form-title" className="st-form__label">
              title:
            </label>
            <select id="st-form-title" className="st-form__input" placeholder="Title" autoComplete="title">
              <option value="Mr">Mr</option>
              <option value="Mrs">Mrs</option>
              <option value="Ms">Ms</option>
              <option value="Miss">Miss</option>
              <option value="Dr">Dr</option>
            </select>
          </div>
        </div>
        <div className="st-form__section st-form__section--horizontal">
          <div className="st-form__field">
            <label htmlFor="st-form-first-name" className="st-form__label">
              first name:{' '}
            </label>
            <input
              type="text"
              name="myBillFirstName"
              id="st-form-first-name"
              className="st-form__input"
              placeholder="John"
              data-st-name="billingfirstname"
              autoComplete="given-name"
            />
          </div>

          <div className="st-form__field">
            <label htmlFor="st-form-last-name" className="st-form__label">
              last name:{' '}
            </label>
            <input
              type="text"
              name="myBillLastName"
              id="st-form-last-name"
              className="st-form__input"
              placeholder="Doe"
              data-st-name="billinglastname"
              autoComplete="family-name"
            />
          </div>
        </div>
        <div className="st-form__section st-form__section--horizontal">
          <div className="st-form__field">
            <label htmlFor="st-form-title" className="st-form__label">
              date of birth:
            </label>
            <input
              type="date"
              name="myBillDateOfBirth"
              id="st-form-date-of-birth"
              className="st-form__input"
              placeholder="myBillDateOfBirth"
              data-st-name="billingdateofbirth"
              autoComplete="date"
            />
          </div>
        </div>
      </fieldset>
    </Layout>
  );
};
export default PersonalData;

// example/vuejs/src/views/PersonalData.vue
<template>
  <PageTitle title="Personal data"/>
  <form class="st-form">
    <fieldset>
      <legend>Personal data</legend>
      <div class="form-row">
        <select class="st-select">
          <option disabled selected hidden>Title</option>
          <option>Mr</option>
          <option>Mrs</option>
          <option>Ms</option>
          <option>Miss</option>
          <option>Dr</option>
        </select>
        <input type="text" placeholder="First name" class="st-input" />
        <input type="text" placeholder="Last name" class="st-input" />
      </div>
      <div class="form-row">
        <input type="date" placeholder="Date of birth" class="st-input" />
      </div>
    </fieldset>
    <div class="form-row">
      <button type="submit"
              class="st-button"
              @click="$router.push('contact-data')">Continue
      </button>
    </div>
  </form>
</template>

<script>
import PageTitle from '@/components/PageTitle.vue';

export default {
  name: 'PersonalData',
  components: {
    PageTitle,
  },
};
</script>

<style scoped>

</style>
